### ISSUE TITLE
Publish a release on PyPI

### ISSUE THREAD

**Issue by claudep** [zbohm/python-ooolib#1]
Hi Zdenek,

Do you have a plan to publish a release of your ooolib clone to PyPI? Do you intend to continue maintaining this piece of software?

**Comment by zbohm** [comment]
Hi Claude,
no, I did not have a plan to publish it to PyPI. But I can if it is interest. I can also maintain this sw for some time, but currenty I have no intention of adding anything new.

**Comment by claudep** [comment]
Mmmh... don't know what to do. Now I see there was a new project by J. Colton named odslib, which was then forked here: https://bitbucket.org/angry_elf/odslib, but it also looks like unmaintained. I'm struggling to find good Pythonic, well-maintained library to access OpenDocument (spreadsheet or others). Maybe ezodf (https://github.com/T0ha/ezodf/) might be the most current one?

**Comment by zbohm** [comment]
There is also https://code.google.com/archive/p/odslib-python/ but it is unchanged for a long time.

**Comment by zbohm** [comment]
Hi Claude,
if you still interested, I publish project on https://pypi.org/project/ooolib-python/.

**Comment by claudep** [comment]
Thanks, that's great news. However I'm most interested in knowing if the project will get serious maintainership or not. That's the key for me!

**Comment by claudep** [comment]
I guess the ticket can be closed now.
